---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    app.quarkus.io/vcs-url: https://github.com/redhat-developer-demos/millionaire-backend.git
    app.quarkus.io/build-timestamp: 2020-10-21 - 09:00:24 +0000
    app.quarkus.io/commit-id: 83c3df2e5dc4d46bea31e2d381cabdee3a78a5d7
  labels:
    app.kubernetes.io/name: millionaire-backend
    app.kubernetes.io/version: "2.7"
  name: millionaire-backend
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.quarkus.io/vcs-url: https://github.com/redhat-developer-demos/millionaire-backend.git
    app.quarkus.io/build-timestamp: 2020-10-21 - 09:00:24 +0000
    app.quarkus.io/commit-id: 83c3df2e5dc4d46bea31e2d381cabdee3a78a5d7
    service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: '1800'
  labels:
    app.kubernetes.io/name: millionaire-backend
    app.kubernetes.io/version: "2.7"
  name: millionaire-backend
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/name: millionaire-backend
    app.kubernetes.io/version: "2.7"
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.quarkus.io/vcs-url: https://github.com/redhat-developer-demos/millionaire-backend.git
    app.quarkus.io/build-timestamp: 2020-10-21 - 09:00:24 +0000
    app.quarkus.io/commit-id: 83c3df2e5dc4d46bea31e2d381cabdee3a78a5d7
  labels:
    app.kubernetes.io/name: millionaire-backend
    app.kubernetes.io/version: "2.7"
  name: millionaire-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: millionaire-backend
      app.kubernetes.io/version: "2.7"
  template:
    metadata:
      annotations:
        app.quarkus.io/vcs-url: https://github.com/redhat-developer-demos/millionaire-backend.git
        app.quarkus.io/build-timestamp: 2020-10-21 - 09:00:24 +0000
        app.quarkus.io/commit-id: 83c3df2e5dc4d46bea31e2d381cabdee3a78a5d7
      labels:
        app.kubernetes.io/name: millionaire-backend
        app.kubernetes.io/version: "2.7"
    spec:
      containers:
      - env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: sebi2706/millionaire-backend:2.7
        imagePullPolicy: IfNotPresent
        name: millionaire-backend
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: QUARKUS_OIDC_AUTH_SERVER_URL
              value: >-
                https://keycloak-millionaire.apps.openshift.soto-onaws.com/auth/realms/game
            - name: QUARKUS_OIDC_TLS_VERIFICATION
              value: none
            - name: QUARKUS_LOG_LEVEL
              value: TRACE
            - name: QUARKUS_DATASOURCE_DB_KIND
              value: postgresql
            - name: QUARKUS_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: keycloak-db-secret
                  key: database-username
            - name: QUARKUS_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-db-secret
                  key: database-username-password
            - name: QUARKUS_DATASOURCE_JDBC_URL
              value: >-
                jdbc:postgresql://postgresql:5432/gamedb
            - name: QUARKUS_HIBERNATE_ORM_DATABASE_GENERATION
              value: drop-and-create
      serviceAccount: millionaire-backend
